import { useState } from 'react'
import { Archive, ChevronLeft, ChevronRight, Clipboard, Database, ExternalLink, Folder, Github, Globe2, Pencil, RotateCcw, Server, Trash2, X } from 'lucide-react'
import type { Project } from '../types/project'
import { ProjectLogo } from './ProjectLogo'
import { Modal } from './Modal'

interface Props { project: Project; onClose: () => void; onEdit: () => void; onArchive: () => void; onRestore: () => void; onDelete: () => void; onCopy: (value: string, kind: '链接' | '路径') => void }
export function ProjectDrawer({ project, onClose, onEdit, onArchive, onRestore, onDelete, onCopy }: Props) { const [selected, setSelected] = useState(0); const screens = [...project.screenshots].sort((a, b) => a.sortOrder - b.sortOrder); const current = screens[selected]; return <div className="drawer-wrap"><div className="drawer-backdrop" onClick={onClose} /><aside className="drawer" role="dialog" aria-modal="true" aria-label={`${project.name} 项目详情`}><header className="drawer-header"><div><span>项目详情</span><h2>{project.name}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭详情"><X size={20} /></button></header><div className="drawer-actions">{!project.archived && <button type="button" onClick={onEdit}><Pencil size={15} />编辑</button>}{project.archived ? <button type="button" onClick={onRestore}><RotateCcw size={15} />恢复</button> : <button type="button" onClick={onArchive}><Archive size={15} />归档</button>}<button type="button" className="danger-text" onClick={onDelete}><Trash2 size={15} />删除</button></div><div className="drawer-body"><section className="detail-hero"><ProjectLogo project={project} size="large" /><div><span className={`status-badge status-${project.status}`}>● {project.status}</span><p>{project.category}</p></div></section><p className="detail-brief">{project.brief || '还没有填写项目简介。'}</p><InfoGrid project={project} /><section className="detail-section"><div className="section-title"><h3>项目截图</h3>{screens.length > 0 && <span>{selected + 1} / {screens.length}</span>}</div>{current ? <div className="gallery"><img src={current.imageUrl} alt={current.label} /><div className="gallery-nav"><button type="button" aria-label="上一张截图" disabled={selected === 0} onClick={() => setSelected(selected - 1)}><ChevronLeft size={18} /></button><span>{current.label}</span><button type="button" aria-label="下一张截图" disabled={selected === screens.length - 1} onClick={() => setSelected(selected + 1)}><ChevronRight size={18} /></button></div><div className="thumbnails">{screens.map((shot, index) => <button type="button" className={index === selected ? 'selected' : ''} onClick={() => setSelected(index)} key={shot.id}><img src={shot.imageUrl} alt={shot.label} /></button>)}</div></div> : <div className="drawer-empty">尚未添加项目截图</div>}</section><ResourceLinks project={project} onCopy={onCopy} /></div></aside></div> }
function InfoGrid({ project }: { project: Project }) { const date = (value: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)) : '未设置'; return <section className="info-grid"><span>上线时间<b>{date(project.launchDate)}</b></span><span>创建时间<b>{date(project.createdAt)}</b></span><span>最近更新<b>{date(project.updatedAt)}</b></span><span>归档状态<b>{project.archived ? '已归档' : '进行中'}</b></span></section> }
function ResourceLinks({ project, onCopy }: { project: Project; onCopy: Props['onCopy'] }) { const links = [{ label: '正式网站', value: project.websiteUrl, icon: Globe2 }, { label: 'GitHub 仓库', value: project.githubUrl, icon: Github }, { label: 'Vercel 部署', value: project.vercelUrl, icon: Server }, { label: 'Supabase 后台', value: project.supabaseUrl, icon: Database }, { label: '本地文件夹路径', value: project.localPath, icon: Folder }].filter((item): item is { label: string; value: string; icon: typeof Globe2 } => Boolean(item.value)); return <section className="detail-section"><div className="section-title"><h3>项目资源</h3></div>{links.length ? <div className="resource-list">{links.map(({ label, value, icon: Icon }) => <div key={label}><Icon size={17} /><span><small>{label}</small><b title={value}>{value}</b></span><button type="button" aria-label={`复制${label}`} onClick={() => onCopy(value, label === '本地文件夹路径' ? '路径' : '链接')}><Clipboard size={16} /></button>{label !== '本地文件夹路径' && <a href={value} target="_blank" rel="noopener noreferrer" aria-label={`在新标签页打开${label}`}><ExternalLink size={16} /></a>}</div>)}</div> : <div className="drawer-empty">尚未配置项目资源</div>}</section> }
export function DeleteDialog({ project, onCancel, onConfirm }: { project: Project; onCancel: () => void; onConfirm: () => void }) { return <Modal title="确认删除" onClose={onCancel} className="confirm-modal"><p>确定删除 <strong>{project.name}</strong> 吗？该操作无法撤销。</p><div className="confirm-actions"><button type="button" className="secondary-button" onClick={onCancel}>取消</button><button type="button" className="danger-button" onClick={onConfirm}>确认删除</button></div></Modal> }
