import { useEffect, useMemo, useState } from 'react'
import { LayoutGrid } from 'lucide-react'
import { Header } from './components/Header'
import { ProjectControls } from './components/ProjectControls'
import { ProjectCard, ProjectList } from './components/ProjectCard'
import { EmptyState } from './components/EmptyState'
import { ProjectDrawer, DeleteDialog } from './components/ProjectDrawer'
import { ProjectForm } from './components/ProjectForm'
import { Toast, type ToastMessage } from './components/Toast'
import { dataMode, repository } from './lib/repository'
import type { Project, ProjectCategory, ProjectInput, ProjectStatus, SortMode, ViewMode } from './types/project'

const readStored = <T,>(key: string, fallback: T): T => { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback }
export default function App() { const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [category, setCategory] = useState<ProjectCategory | '全部'>('全部'); const [status, setStatus] = useState<ProjectStatus | '全部'>('全部'); const [sort, setSort] = useState<SortMode>('updated'); const [archived, setArchived] = useState(false); const [view, setViewState] = useState<ViewMode>(() => readStored('sugar-project-hub.view', 'grid')); const [theme, setTheme] = useState<'light' | 'dark'>(() => readStored('sugar-project-hub.theme', 'light')); const [selected, setSelected] = useState<Project | null>(null); const [formProject, setFormProject] = useState<Project | undefined | null>(null); const [deleting, setDeleting] = useState<Project | null>(null); const [toast, setToast] = useState<ToastMessage | null>(null)
  const notify = (text: string, kind: ToastMessage['kind'] = 'success') => setToast({ id: Date.now(), text, kind })
  useEffect(() => { let active = true; void repository.getAll().then((items) => { if (active) setProjects(items) }).catch((error: unknown) => { if (active) setToast({ id: Date.now(), text: error instanceof Error ? error.message : '加载失败', kind: 'error' }) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, []); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('sugar-project-hub.theme', JSON.stringify(theme)) }, [theme]); useEffect(() => { localStorage.setItem('sugar-project-hub.view', JSON.stringify(view)) }, [view]); useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2800); return () => window.clearTimeout(timer) }, [toast])
  const visible = useMemo(() => projects.filter((project) => { const target = `${project.name} ${project.brief} ${project.category}`.toLocaleLowerCase(); return project.archived === archived && target.includes(query.toLocaleLowerCase()) && (category === '全部' || project.category === category) && (status === '全部' || project.status === status) }).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'zh-CN') : sort === 'created' ? new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime() : sort === 'launched' ? (b.launchDate ?? '').localeCompare(a.launchDate ?? '') : new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [projects, archived, query, category, status, sort])
  const activeProjects = projects.filter((project) => !project.archived)
  const save = async (input: ProjectInput) => { if (formProject) { const saved = await repository.update(formProject.id, input); setProjects((items) => items.map((item) => item.id === saved.id ? saved : item)); setSelected(saved); notify('项目修改成功') } else { const saved = await repository.create(input); setProjects((items) => [saved, ...items]); notify('项目创建成功') } }
  const archive = async (project: Project, archivedState: boolean) => { const saved = await repository.archive(project.id, archivedState); setProjects((items) => items.map((item) => item.id === project.id ? saved : item)); setSelected(null); notify(archivedState ? '项目已归档' : '项目已恢复') }
  const remove = async () => { if (!deleting) return; await repository.remove(deleting.id); setProjects((items) => items.filter((item) => item.id !== deleting.id)); setSelected(null); setDeleting(null); notify('项目删除成功') }
  const copy = async (value: string, kind: '链接' | '路径') => { try { await navigator.clipboard.writeText(value); notify(`${kind}已复制`) } catch { notify('复制失败，请手动复制', 'error') } }
  const clear = () => { setQuery(''); setCategory('全部'); setStatus('全部'); setArchived(false) }
  return <><Header query={query} setQuery={setQuery} view={view} setView={setViewState} theme={theme} toggleTheme={() => setTheme((current) => current === 'light' ? 'dark' : 'light')} onCreate={() => setFormProject(undefined)} /><main className="app-shell"><div className="page-heading"><div><p>项目总览</p><h1>让每一个想法，都有清晰的归处。</h1></div><span className="data-mode"><LayoutGrid size={15} />{dataMode} 模式</span></div><ProjectControls category={category} setCategory={setCategory} status={status} setStatus={setStatus} sort={sort} setSort={setSort} projects={activeProjects} archived={archived} setArchived={setArchived} /><section className="results-heading"><div><h2>{archived ? '归档项目' : '全部项目'}</h2><span>{loading ? '正在整理…' : `${visible.length} 个项目`}</span></div>{archived && <p>归档项目不会出现在日常总览中，可以随时恢复。</p>}</section>{!loading && (visible.length ? view === 'grid' ? <div className="project-grid">{visible.map((project) => <ProjectCard project={project} key={project.id} onOpen={() => setSelected(project)} />)}</div> : <ProjectList projects={visible} onOpen={setSelected} /> : <EmptyState searching={Boolean(query || category !== '全部' || status !== '全部' || archived)} onClear={clear} onCreate={() => setFormProject(undefined)} />)}</main>{selected && <ProjectDrawer project={selected} onClose={() => setSelected(null)} onEdit={() => setFormProject(selected)} onArchive={() => void archive(selected, true)} onRestore={() => void archive(selected, false)} onDelete={() => setDeleting(selected)} onCopy={copy} />}{formProject !== null && <ProjectForm project={formProject ?? undefined} onClose={() => setFormProject(null)} onSave={save} notify={notify} />}{deleting && <DeleteDialog project={deleting} onCancel={() => setDeleting(null)} onConfirm={() => void remove()} />}<Toast toast={toast} /></> }
